### ISSUE TITLE
Warning produced running job

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/open-data-etl-utility-kit#21]
Right now, a successful completion of a Kettle ETL for the portal will produce the following warning:

> WARNING: -h,--fileToPublishHasHeaderRow is being ignored because -sc,--pathToFTPControlFile or -cf,--pathToControlFile was supplied.Publishing

ETLs will succeed, but will only recognize the control file settings.

Just need to fix the `ETL/Utilities/DataSyncHTTP.ktr` step which compiles the DataSync command.

**Comment by levyj** [comment]
I have made the change and am testing on our system before updating this repository.
