### ISSUE TITLE
Support log-analysis utilities on Windows

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/open-data-etl-utility-kit#3]
This repository contains three Bash scripts that help ETL administrators analyze the contents of Kettle/Pentaho log files: (1) [A_DatasetLogs.sh](https://github.com/Chicago/open-data-etl-utility-kit/blob/master/Log/A_DatasetLogs.sh) (2) [A_ETLRuntimes.sh](https://github.com/Chicago/open-data-etl-utility-kit/blob/master/Log/A_ETLRuntimes.sh) (3) [A_Today.sh](https://github.com/Chicago/open-data-etl-utility-kit/blob/master/Log/A_TodayLogs.sh)

These should be converted to support Windows environment, likely use .bat files with similar functionality.

**Comment by lgwapnitsky** [comment]
are you still looking for input on these?  THis can be done using PowerShell very easily.

Thank you

**Comment by levyj** [comment]
Yes. Noting dependencies in the documentation would be helpful.

Thanks.

**Comment by lgwapnitsky** [comment]
can you provide samples of the data that will be enumerated?

**Comment by tomschenkjr** [comment]
Sorry, didn't understand the question -- samples of the log files?

**Comment by lgwapnitsky** [comment]
What types of files are these scripts run on? It would be good to have
sample output on which to test.

*Larry G. Wapnitsky*


*E: Larry@Wapnitsky.com*

*Web: Larry.Wapnitsky.com <http://Larry.Wapnitsky.com>Twitter:
@LGWapnitsky**PGP Public
Key <http://larry.wapnitsky.com/larry_wapnitsky_key.txt>*

**Comment by jefw** [comment]
Chipping away at this one for you.  Have first 3 of 4 done, will create a pull request when I finish the last.

**Comment by jefw** [comment]
Completed.  Issued pull request for [Issue 3](https://github.com/Chicago/open-data-etl-utility-kit/pull/30).
