### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by eccoilmoro** [Chicago/open-data-etl-utility-kit#37]
Hi all,
I cloned your repo for instruction purposes and to make some tests. I don't understand where the environment variables are set. For example the variable **P_Sender_Address**, I don't find a config file that sets this variable and the others; in the documentation it's not explained. Perhaps I'm missing something!
Thanks in advance for your help. 
Franco

**Comment by levyj** [comment]
Hi Franco,

The setting for `P_Sender_Address` is in the parameters setting of `ETL_Completion_E-Mail.ktr`. See http://open-data-etl-utility-kit.readthedocs.io/en/latest/installation-configuration.html#setting-up-email.

As a general rule, something starting with `P_` is a parameter setting in some KTR file, often set to a default value but sometimes expecting a value from the calling step (or both -- defaulted but able to be overridden).

Ideally, we have documented most/all parameters that one would need to set.  If we have not, definitely let us know but, in order not to be blocked while waiting for us to reply, a full search of the repo for the parameter value should turn up the files in which it appears.

Thanks for the note and good luck using the project.  Please let us know if you have any questions and we encourage enhancements/corrections via pull request.

Closing but feel free to re-open.

Jon
